-- MySQL Script generated by MySQL Workbench
-- Wed Feb 28 00:11:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

drop database dw_systrxbanco;

CREATE DATABASE dw_systrxbanco;
USE dw_systrxbanco;

-- -----------------------------------------------------
-- Table `mydb`.`DIM_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DIM_CLIENTE (
  `idclienteSK` INT NOT NULL,
  `nrodocumento` VARCHAR(8) NULL,
  `nbrcli` VARCHAR(50) NULL,
  `email` VARCHAR(30) NULL,
  `nrocuenta` VARCHAR(30) NULL,
  PRIMARY KEY (`idclienteSK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_TIPCARGOABONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DIM_TIPCARGOABONO (
  `idcargoabonoSK` INT NOT NULL,
  `nbrcargoabono` VARCHAR(30) NULL,
  PRIMARY KEY (`idcargoabonoSK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_OPERADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DIM_OPERADOR (
  `idoperadorSK` INT NOT NULL,
  `codoperador` VARCHAR(10) NULL,
  `nbrtipooperador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idoperadorSK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_CANAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DIM_CANAL (
  `idcanalSK` INT NOT NULL,
  `nbrcanal` VARCHAR(100) NULL,
  PRIMARY KEY (`idcanalSK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_TIPOTRANSACCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DIM_TIPOTRANSACCION (
  `idtipotransaccionSK` INT NOT NULL,
  `nbrtiptransaccion` VARCHAR(100) NULL,
  PRIMARY KEY (`idtipotransaccionSK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_SUCURSAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DIM_SUCURSAL (
  `idsucursalSK` INT NOT NULL,
  `codsucursal` VARCHAR(10) NULL,
  `nbrsucursal` VARCHAR(100) NULL,
  PRIMARY KEY (`idsucursalSK`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIM_TIEMPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DIM_TIEMPO (
  `idfechaSK` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `anio` INT NULL,
  `mes` INT NULL,
  `dia` INT NULL,
  `semana` INT NULL,
  `mes_nombre` VARCHAR(45) NULL,
  `dia_semana` VARCHAR(45) NULL,
  PRIMARY KEY (`idfechaSK`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`FACT_TRANSACCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FACT_TRANSACCIONES (
  `DIM_CLIENTE_idclienteSK` INT NOT NULL,
  `DIM_TIPCARGOABONO_idcargoabonoSK` INT NOT NULL,
  `DIM_OPERADOR_idoperadorSK` INT NOT NULL,
  `DIM_CANAL_idcanalSK` INT NOT NULL,
  `DIM_TIPOTRANSACCION_idtipotransaccionSK` INT NOT NULL,
  `DIM_SUCURSAL_idsucursalSK` INT NOT NULL,
  `DIM_FECHA_idfechaSK` INT NOT NULL,
  `fecha` DATE NULL,
  `anio` INT NULL,
  `mes` INT NULL,
  `dia` INT NULL,
  `semana` INT NULL,
  `mes_nombre` VARCHAR(45) NULL,
  `dia_semana` VARCHAR(45) NULL,
  `modelotran` VARCHAR(45) NULL,
  `monto` VARCHAR(45) NULL,
  `flgtranvalida` INT NULL,

  INDEX `fk_FACT_TRANSACCIONES_DIM_CLIENTE1_idx` (`DIM_CLIENTE_idclienteSK` ASC) VISIBLE,
  INDEX `fk_FACT_TRANSACCIONES_DIM_TIPCARGOABONO1_idx` (`DIM_TIPCARGOABONO_idcargoabonoSK` ASC) VISIBLE,
  INDEX `fk_FACT_TRANSACCIONES_DIM_OPERADOR1_idx` (`DIM_OPERADOR_idoperadorSK` ASC) VISIBLE,
  INDEX `fk_FACT_TRANSACCIONES_DIM_CANAL1_idx` (`DIM_CANAL_idcanalSK` ASC) VISIBLE,
  INDEX `fk_FACT_TRANSACCIONES_DIM_TIPOTRANSACCION1_idx` (`DIM_TIPOTRANSACCION_idtipotransaccionSK` ASC) VISIBLE,
  INDEX `fk_FACT_TRANSACCIONES_DIM_SUCURSAL1_idx` (`DIM_SUCURSAL_idsucursalSK` ASC) VISIBLE,
  INDEX `fk_FACT_TRANSACCIONES_DIM_FECHA1_idx` (`DIM_FECHA_idfechaSK` ASC) VISIBLE,
  CONSTRAINT `fk_FACT_TRANSACCIONES_DIM_CLIENTE1`
    FOREIGN KEY (`DIM_CLIENTE_idclienteSK`)
    REFERENCES DIM_CLIENTE (`idclienteSK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_TRANSACCIONES_DIM_TIPCARGOABONO1`
    FOREIGN KEY (`DIM_TIPCARGOABONO_idcargoabonoSK`)
    REFERENCES DIM_TIPCARGOABONO (`idcargoabonoSK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_TRANSACCIONES_DIM_OPERADOR1`
    FOREIGN KEY (`DIM_OPERADOR_idoperadorSK`)
    REFERENCES DIM_OPERADOR (`idoperadorSK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_TRANSACCIONES_DIM_CANAL1`
    FOREIGN KEY (`DIM_CANAL_idcanalSK`)
    REFERENCES DIM_CANAL (`idcanalSK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_TRANSACCIONES_DIM_TIPOTRANSACCION1`
    FOREIGN KEY (`DIM_TIPOTRANSACCION_idtipotransaccionSK`)
    REFERENCES DIM_TIPOTRANSACCION (`idtipotransaccionSK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_TRANSACCIONES_DIM_SUCURSAL1`
    FOREIGN KEY (`DIM_SUCURSAL_idsucursalSK`)
    REFERENCES DIM_SUCURSAL (`idsucursalSK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_TRANSACCIONES_DIM_FECHA1`
    FOREIGN KEY (`DIM_FECHA_idfechaSK`)
    REFERENCES DIM_TIEMPO (`idfechaSK`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

